### ISSUE TITLE
Use of ::ng-deep is applying styles globally

### ISSUE THREAD

**Issue by jordandh** [tiaguinho/material-community-components#123]
**Describe the bug**
The color-picker and timer-picker components are using the ::ng-deep selector to apply styles to material components globally.

**To Reproduce**
1. Go to mcc documentation website
2. Go to the timer-picker example
3. Open a timer-picker
4. Inspect a mat-icon-button in the timer-picker
5. Scroll through the styles until you find global styles being applied by the timer-picker component
```css
.mat-icon-button {
    width: 30px;
    height: 30px;
    line-height: 30px;
}
```

**Expected behavior**
I expect the library to not change styles outside of its own components.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 80
